---
title: "Confidence in US Institutions from Pre to Post-Pandemic"
subtitle: "STATS 506 Final Project"
title-fontstyle: "large" 
subtitle-fontstyle: "small"
author: "Sydney Yeomans"
author-fontstyle: "small"
format:
  pdf:
    geometry:
      - top=1cm
      - bottom=1cm
      - left=1.5cm
      - right=1.5cm
editor: visual
---

\vspace{-2.0cm}

## Introduction 
Public confidence in institutions evolves over time and is influenced by major national events and politics. The COVID-19 pandemic was the most recent event that altered everyday life, including social, economic, and political environments, and potentially changed Americans' trust in their government's institutions. This project investigates how Americans' confidence in major government programs and institutions (i.e., the Military, Congress, Supreme Court, and Executive Branch) has changed from pre-pandemic (2012-2018) to during the pandemic (2021-2022) and post-pandemic (2023-2024) \footnote{The during and post periods are combined and referred to as post-pandemic for efficiency.}. Using data from the General Social Survey (GSS), this study will examine whether these patterns differ across demographic groups such as race and sex

## Methods 
This project utilizes publicly available data from the General Social Survey (GSS), conducted by the National Opinion Research Center (NORC), which is associated with the University of Chicago. The GSS includes data from 1972 to 2024 and contains a standard set of demographic, behavioral, and attitudinal questions, plus any topics of special interest. There are various questions that ask about the respondents confidence in government organizations and institutions. The question they ask the respondent's in regards to confidence is the following, ``I am going to name some institutions in this country. As far as the people running these institutions are concerned, would you say you have a great deal of confidence (1), only some confidence (2), or hardly any confidence (3) at all in them?'' \cite{survey_q} \footnote{The numbers in parenthesis are the codes for such responses.}.

NORC does not provide their design-adjusted weights due to wanting to keep confidentiality and protection for the respondents. Instead they add weights to the public data set adjusted by population controls, specifically, they add the post-stratification weight variables WTSSPS and WTSSNRPS. It is very important to use these weights to get more representative results, and since this project is using years $2012-2024$, the weight WTSSNRPS is used, which is available for years $2004-2024$ \footnote{For more information about this weight variable please see the GSS documentation}.   

Exploratory data analysis revealed that the GSS has moved away from yearly surveys and provided some very interesting insights by making plots to see how the average response to the question on confidence changes over the years. From this we saw that confidence in the Supreme Court had smaller averages compared pre-pandemic meaning there was less confidence in this system than after. We also saw this to be the case for confidence in the Military. There is notable volatility in the average confidence in the Executive Branch of Government and Congress. After data cleaning, we end up with $20,612$ observations on $6,906$ variables.

To formally test if differences exist between the two periods, statistical models and testing were used. To start, a chi-squared test of independence was used to see if an association existed between period and the confidence in the institutions of interest. Once this was established, a generalized linear model (GLM) was used to see if this association was significant and to give it magnitude. Once this was done, we added in demographic information that could be playing a role in people's confidence in these institutions.  


## Analysis and Results
The chi-square test of independence revealed if the confidence in our institutions of interest were associated with time period, which is this case was pre-pandemic and during/post-pandemic. After running these tests, we found that there is an association for confidence and period for the Supreme Court, the Executive Branch of Government, and the Military. This means that we would reject the null of the chi-square test, that our two categorical variables are independent (i.e. no association). We would conclude that these variables are not independent. The variable for the confidence in Congress was not significant, meaning we fail to reject the null. Therefore, confidence in Congress and period show no association. Although we were able to find an association we do not know what this association is.  

To find out the type of association we found with the chi-square tests, we used generalized linear models (GLM), using a normal link to examine how confidence scores changed across periods. Starting with confidence in the Supreme Court, we found a statistically significant result, with a p-value of $<2e^{-16}$, that showed pre-pandemic confidence was $0.21$ points lower than post-pandemic, showing there was more confidence before the pandemic. Next, the confidence in the Executive Branch showed similar significant results (p-value of $0.0039$), pre-pandemic confidence was $0.04$ points less than post-pandemic, but this result is not very big in magnitude. Congress was found not to be associated with period and the GLM results are consistent with this, producing a non-significant p-value. The confidence in the Military shows similar trends as the first two, with it being statistically significant (p-value of $<2e^{-16}$) and having more confidence in this institution pre-pandemic with a coefficient of $-0.13611$. Therefore, we see that confidence in government institutions was higher in the pre-pandemic period.  


```{r}
#| echo: false
#| message: false
#| warning: false
#| label: fig-myplot
#| fig-cap: "Weighted average confidence plots over time seperated by insitution of interest."
library(tidyverse)
library(ggplot2)
library(dplyr)
library(data.table)
library(haven)
gss <- read_sas("gss7224_r2.sas7bdat")
gss$YEAR <- as.numeric(gss$YEAR)
conf_vars <- c("CONFED","CONJUDGE","CONLEGIS","CONARMY")
gss <- gss %>%
  mutate(across(all_of(conf_vars), ~replace(., . %in% c(8, 9, 0), NA)))

#Set up years of interest
years_pre  <- 2012:2018
years_dur <- c(2021, 2022, 2023, 2024)
gss_pre <- gss %>%
  filter(YEAR %in% years_pre)

#Subset for the during and post pandemic dates
gss_dur <- gss %>%
  filter(YEAR %in% years_dur)
gss_pre <- gss_pre %>%
  mutate(weight = WTSSNRPS,
         period = "Pre-pandemic")

gss_dur <- gss_dur %>%
  mutate(weight = WTSSNRPS,
         period = "During/Post-Pandemic")
gss_fin <- bind_rows(gss_pre, gss_dur)
gss_fin <- gss_fin %>%
  mutate(across(all_of(conf_vars), ~replace(., . %in% c(8,9, 0), NA)))
gss_fin$SEX  <- factor(gss_fin$SEX, levels = c(1,2),
                       labels = c("Male", "Female"))
conf_labels <- c(CONJUDGE = "Supreme Court", CONLEGIS = "Congress",
                 CONFED   = "Executive Branch", CONARMY  = "Military")

gss_long <- gss_fin %>%
            select(YEAR, period, weight, all_of(names(conf_labels))) %>%
            pivot_longer(cols = all_of(names(conf_labels)),
                         names_to = "institution",
                         values_to = "confidence") %>%
            mutate(institution = conf_labels[institution])

summary_long <- gss_long %>%
                group_by(institution, period, YEAR) %>%
                summarize(mean_conf = weighted.mean(confidence, weight, na.rm = TRUE),
                          .groups = "drop") %>%
                ungroup()

ggplot(summary_long, aes(x = YEAR, y = mean_conf, color = period)) +
  geom_line(linewidth = 1) + 
  geom_point(size = 2) +
  facet_wrap(~ institution, scales = "fixed") +
  scale_x_continuous(breaks = summary_inst$YEAR) +
  scale_y_continuous(limits = c(1, 3), breaks = 1:3,
    labels = c("A great deal", "Only some", "Hardly any")) +
  labs(title = "Weighted Average Confidence in U.S. Institutions",
       x = "Year",
       y = "Weighted Average Confidence",
       color = "Period") +
  theme_minimal(base_size = 12) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 7))
```

We next examined whether demographic characteristics affected these confidence patterns by including sex and race in the GLMs. This revealed similar patterns to the simple model, but we do see some notable changes when including the respondent's sex and race. The reference group is post-pandemic, male, and white. Starting with the Supreme Court, we see that the pre-pandemic period showed higher confidence holding other variables constant, which follows the results of the simple model. Females seemed to trust the Supreme Court less than males post-pandemic holding race constant, which makes sense since Roe v. Wade was overturned in $2022$. The same is true for respondents who were Black, while the Other group had slightly higher confidence than the reference group. All results for the Supreme Court were significant. Confidence in the Executive Branch of Government was seen to be higher pre-pandemic holding all else constant, matching previous results. Females results showed females post-pandemic were more confident in this branch of government, but the results were not significant, showing that the difference between males and females for the Executive Branch can't be said to exist. Respondents that fell into the Black and Other racial category showed higher confidence in the Executive branch than our reference group post-pandemic with significant results. This could possibly be due to the political party of the sitting president switching to a Democrat, in which a majority of people who fall into these categories vote for. The results for Congress showed differing results compared to the simple model. Before, the period variable for Congress had non-significant results, however, after factoring in sex and race we see these results are now significant and pre-pandemic can be seen to have slightly higher confidence, holding other factors constant. The other demographic variables are all significant and show higher confidence post-pandemic since all their coefficients are negative, possibly due political undertones. Lastly, the Military pre-pandemic was seen to have more confidence holding everything else constant, which was seen first in the simple model. Adding in demographic information, it is seen the respondents post-pandemic had slightly less confidence in the Military as seen by the positive coefficients they have, holding all else constant. From these results, we can see that demographic information plays a role in the patterns we see for the confidence in major institutions.

## Discussion
In this paper, we explored how the confidence in major institutions in the US changed from pre-pandemic to during/post-pandemic. The results consistently showed that across institutions, pre-pandemic confidence was generally higher. We also saw that demographic factors moderate confidence levels and these factors sometimes amplifying or reducing the period differences that were observed in the simpler models. 

Despite the insights gained, there are some limitations that should be addressed. First, while survey weights and design adjustments were used to make the data more representative, this work only included $20,000$ observations meaning these results should not be generalized to the million of US citizens. Second, missing data and the removal of "don’t know" or non-responses may introduce bias and affected the confidence estimates, once again making the data not fully representative of the whole US population. Lastly, due to the gaps in survey years, the during the pandemic years were added and this could have altered the results. Future work should look to overcome these limitations. On top of this, political party affiliation of either the respondent or the sitting President were not included. This would most likely offer additional explanation to confidence patterns and should be looked into in future work.

In conclusion, the pandemic represents a notable disruption that influenced Americans’ confidence in Government institutions. These shifts highlight the dynamic nature of public trust, and with many ongoing societal and political changes, we should keep an eye on these trends in the coming years. 

\clearpage
Github URL: \url{https://github.com/syeomans0/STATS-506-Final-Project.git}
\\
\begin{thebibliography}{99}

\bibitem{survey_q}
Smith, Tom W., Davern, Michael, Freese, Jeremy, and Stephen L. Morgan. General Social Surveys, 1972-2018, Cumulative Codebook. Principal Investigator, Tom W. Smith; Co-Principal Investigators, Michael Davern, Jeremy Freese
and Stephen L. Morgan, NORC ed. Chicago: NORC, 2019. 1 data file (64,814 logical records) and 1 codebook (3,758 pp).

\bibitem{survey_wgt}
Vegetti, F. Survey Weights with R. Survey Statistics – Day 2. \url{https://federicovegetti.github.io/teaching/heidelberg_2018/lab/sst_lab_day2.html}

\bibitem{chi_sqr} 
User Dpel, and Pasek , J. (2018, June 26). Contingency Table P values using R base, Weights and Survey. Stack Overflow. \url{https://stackoverflow.com/questions/50396708/contingency-table-p-values-using-r-base-weights-and-survey}

\bibitem{chat_gpt}
Attribution of Sources: ChatGPT was used when I ran into issues. First, including the averages on top of my individual summary plots. Then when I ran into factor issues with my GLM models that included sex and race, it helped me understand why my survey design failed to work after the conversion to factors and it also helped with my interaction plots since I tried to use code following the STATS 250 labs I taught, but it was not working. Lastly, it helped prepare my data to be faceted correctly (the pivot long) for the plot included in the report.

\end{thebibliography}
